name       : codespell
version    : 2.2.1
release    : 1
source     :
    - https://pypi.io/packages/source/c/codespell/codespell-2.2.1.tar.gz : 569b67e5e5c3ade02a1e23f6bbc56c64b608a3ab48ddd943ece0a03e6c346ed1
homepage   : https://github.com/codespell-project/codespell
license    : GPL-2.0-only
component  : programming.python
summary    : Fix common misspellings in source code
description: |
    Fix common misspellings in text files. It's designed primarily for checking misspelled words in source code, but it can be used with other files as well
builddeps  :
    - pkgconfig(python3)
setup      : |
    %python3_setup
install    : |
    %python3_install
